### ISSUE TITLE
create_cf_environment issues

### ISSUE THREAD

**Issue by locduc-zenfolio** [SAP-samples/cp-cli-automate-operations#1]
Hi SAP team,

I've run & updated script base on step by step this ULR https://developers.sap.com/tutorials/cp-cli-automate-operations.html

when I run to "create_cf_environment", I've a problem with this command 

The problem as the image below:

![image](https://user-images.githubusercontent.com/76542106/112714968-c954ee80-8f0f-11eb-8c7c-af08d9fef808.png)

Please help & advice on it

Thank you
Loc Ta

**Comment by michal-keidar** [comment]
@locduc-zenfolio please try executing the command with:
`btp create accounts/environment-instance --subaccount "$subaccount_id" --environment cloudfoundry --service cloudfoundry --plan standard --parameters "{\"instance_name\":\"$display_name\"}"`

Let me know if this worked for you.
Regards,
Michal.

**Comment by locduc-zenfolio** [comment]
Thank you for your support

It's working well 

Thank you again
Loc Ta

**Comment by michal-keidar** [comment]
Fixed
